### PR TITLE
STRONG-9: add text coloring for user input

### LINKED ISSUE #12: Improve view to highlight incorrect characters

### PR DESCRIPTION
**Pull request by JoshVasilevsky**
Add coloring to user input on correct, wrong, not reached characters

Honestly, we could shorten this code a lot. Assuming we have a cursor with an index we can write the colors directly during input.

Preview:
image

### CODE REVIEW

File: src/main.go [hunk 1]
```diff
@@ -82,15 +96,34 @@ func (m model) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
 }
 
 func (m model) View() string {
-	result := strings.Join(TARGET_WORDS, " ") + "\n" + strings.Join(m.prevWords, " ")
+	return m.RenderUserInput()
```
Comment (andrewjleung) [inline src/main.go]: Can we put the body of `RenderUserInput` into here directly?

File: src/styles.go [hunk 2]
```diff
@@ -0,0 +1,9 @@
+package main
+
+import "github.com/charmbracelet/lipgloss"
+
+var (
+	CorrectTextStyle   = lipgloss.NewStyle().Foreground(lipgloss.Color("#FFFFFF"))
+	WrongTextStyle     = lipgloss.NewStyle().Foreground(lipgloss.Color("#FF0000"))
+	UnreachedTextStyle = lipgloss.NewStyle().Foreground(lipgloss.Color("#808080"))
+)
```
Comment (andrewjleung) [inline src/styles.go]: VERY NICE

File: src/main.go [hunk 3]
```diff
@@ -82,15 +96,34 @@ func (m model) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
...
+		for i := 0; i < int(math.Min(float64(len(targetWord)), float64(len(userWord)))); i++ {
+			textStyle := CorrectTextStyle
+			if targetWord[i] != userWord[i] {
+				textStyle = WrongTextStyle
+			}
+			resp += textStyle.Render(string(targetWord[i]))
+		}
+
+		if len(userWord) > len(targetWord) {
+			resp += WrongTextStyle.Render(string(userWord[len(targetWord):]))
```
Comment (andrewjleung) [inline src/main.go]: Not to be the "it has to be like monkeytype!" guy but can we use a slightly different shade of red rather than `WrongTextStyle` here? Something like `ExtraTextStyle` to indicate that the user word has gone past the target?

Like this:

Screenshot 2023-10-18 at 10 07 29 AM

**Review by andrewjleung — CHANGES_REQUESTED** [review]
Nice work bbg 😭 this works super well. I tried not to be nitpicky about readability things but let me know if you want me to be.

Just have a couple of easy-change suggestions that I think will put the cherry on top.

**Comment by andrewjleung** [comment]
> Assuming we have a cursor with an index we can write the colors directly during input.

This might end up being more complicated considering that we'd have to write portions of the target words to the user words with colors or still do logic to resolve the partial text and extra text cases in the view. Plus, I think we should avoid coupling the view with the model.

File: src/main.go [hunk 4]
```diff
@@ -82,15 +96,34 @@ func (m model) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
...
 
 func (m model) View() string {
-	result := strings.Join(TARGET_WORDS, " ") + "\n" + strings.Join(m.prevWords, " ")
+	return m.RenderUserInput()
+}
 
-	if len(m.prevWords) > 0 {
-		result += " "
-	}
+func (m model) RenderUserInput() string {
```
Comment (aaronewing) [inline src/main.go]: Going forward, can we add comments to new features on PR's? Would be helpful for those learning (ME LOL) and helps cut down on time to understand. Doesn't have to be overboard unless you want it to be. How @andrewjleung handled the update is good

File: src/main.go [hunk 5]
```diff
@@ -82,15 +96,34 @@ func (m model) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
...
+	var resp string
+	for indx, word := range m.targetWords {
+		targetWord := []rune(word)
+		userWord := []rune(m.getUserWordAtIndex(indx))
 
-	result += m.currWord
+		for i := 0; i < int(math.Min(float64(len(targetWord)), float64(len(userWord)))); i++ {
```
Comment (aaronewing) [inline src/main.go]: Asking for understanding sake, The for loop only iterates if the the iterator (i) is less than the length of which ever word between targetWord and userWord is smaller in length? And we are doing this because a correct word can only be correct for the length of the target?

File: src/main.go (hunk 1 above)
Comment (aaronewing) [reply src/main.go]: I kinda disagree with this Andrew, I feel like it helps readability personally by keeping it isolated in its own func. Although to be fair I'm of the school that most of this logic should not be in main.go. (Not saying we shouldn't make this change just offering alternate perspective)

Comment (andrewjleung) [reply src/main.go]: My issue with it is that the purpose of the `View` method is to render the state. The purpose of `RenderUserInput` is also to render the state. I think that the added indirection via a one-line function which just calls another function actually hurts readability because `RenderUserInput` isn't adding any new meaning or abstracting out any functionality, it's instead forcing you to have to jump to another function.

Absolutely in agreement though that eventually once our model/update/view become more complex it should be reorganized out of `main.go`.

File: src/main.go (hunk 5 above)
Comment (JoshVasilevsky) [reply src/main.go]: Its basically to handle printing correctly. We always want to only print the smaller of the target Word and the user word because we can just append the longer word after the loop finishes.

For instance given the following:
TargetWord = aaron
userWord = aarosdfdsgn

We would iterate up until the length of Target word printing the corresponding character to the color of white or red if the letter is correct or not. Then after the loop, we can just append the end of the userWord because it will all be the same color and it is the longer word.

File: src/utils.go [hunk 6]
```diff
@@ -0,0 +1,8 @@
+package main
+
+func min(a, b int) int {
```
Comment (andrewjleung) [inline src/utils.go:3]: Pain... but I see why you had to do it to 'em

File: src/main.go [hunk 7]
```diff
@@ -96,27 +95,29 @@ func (m model) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
...
 			}
 			resp += textStyle.Render(string(targetWord[i]))
 		}
 
+		// determines when to print cursor
+		var cursor string
+		if len(m.prevWords) == indx {
+			cursor = CursorTextStyle.Render("|")
+		}
+
```
Comment (andrewjleung) [inline src/main.go:116]: @aaronewing RIP https://github.com/ideapeople/stronglytyped/pull/10 (though not really because we can still convert things maybe to using bubbles??? Might not be a priority)

File: src/utils.go (hunk 6 above)
Comment (JoshVasilevsky) [reply src/utils.go:3]: no built in int min 😭

File: src/main.go (hunk 7 above)
Comment (JoshVasilevsky) [reply src/main.go:116]: Yeah I just added this cause I realized it was like a couple liner. Y'all can still try to do the bubble thing if you want.

Comment (andrewjleung) [reply src/main.go:116]: Yeah I just tried it out and it is kinda ugly but definitely good for now, we'll still proceed with prettifying it though maybe we should shift our focus to metrics

**Review by andrewjleung — APPROVED** [review]
Nice job LGTM LFG 🚢

File: src/main.go (hunk 7 above)
Comment (aaronewing) [reply src/main.go:116]: im ngl the lipgloss way is 10000000000000000000x better assuming this is from lipgloss

**Review by aaronewing — APPROVED** [review]
